development:
  adapter: postgresql
  database: ifolio_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ifolio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ifolio_production
  pool: 5
  timeout: 5000
