default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['DBUSERNAME'] %>
      password: <%= ENV['DBPASSWORD'] %>
      host:     <%= ENV['DBIP'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production